# Generated by Django 4.1.7 on 2023-03-08 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='profile_pic',
        ),
    ]
